Deploy using terraform

diff --git a/.github/workflows/aca-deploy.yml b/.github/workflows/aca-deploy.yml
--- a/.github/workflows/aca-deploy.yml
+++ b/.github/workflows/aca-deploy.yml
@@ -44,21 +44,111 @@ jobs:
           context: ./
 
 
-  deploy:
+  terraform-plan:
+    name: 'Terraform Plan'
     runs-on: ubuntu-latest
     needs: build
+    defaults:
+      run:
+        working-directory: ./deploy/terraform
     
     steps:
-      - name: Azure Login
-        uses: azure/login@v1
-        with:
-          creds: ${{ secrets.ESHOPDEMO_AZURE_CREDENTIALS }}
+    # Install the latest version of the Terraform CLI
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v2
+      with:
+        terraform_wrapper: false
+    - name: Azure Login
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.ESHOPDEMO_AZURE_CREDENTIALS }}
+    - name: Terraform vars
+      run: | 
+        tee -a terraform.tfvars <<EOF
+        resource_prefix = "eshopdemo"
+        app_image = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
+        EOF
+    - name: Terraform state
+      run: | 
+        tee -a tfstate.tf <<EOF
+        terraform {
+          backend "azurerm" {
+              resource_group_name  = "${{ secrets.TFSTATE_RG }}"
+              storage_account_name = "${{ secrets.TFSTATE_ACCOUNT }}"
+              container_name       = "${{ secrets.TFSTATE_CONTAINER }}"
+              key                  = "${{ secrets.TFSTATE_KEY }}"
+            }
+        }
+        EOF
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init
 
+    # Checks that all Terraform configuration files adhere to a canonical format
+    # Will fail the build if not
+    - name: Terraform Format
+      run: terraform fmt -check
 
-      - name: Deploy to containerapp
-        uses: azure/CLI@v1
-        with:
-          inlineScript: |
-            az config set extension.use_dynamic_install=yes_without_prompt
-            az containerapp registry set -n eshop-demo -g eshop-demo-rg --server docker.io --username  ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
-            az containerapp update -n eshop-demo -g eshop-demo-rg --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi
+        
+    # Save plan to artifacts  
+    - name: Publish Terraform Plan
+      uses: actions/upload-artifact@v3
+      with:
+        name: tfplan
+        path: tfplan
+        
+    # Create string output of Terraform Plan
+    - name: Create String Output
+      id: tf-plan-string
+      run: |
+        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+        
+        delimiter="$(openssl rand -hex 8)"
+        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+        echo "" >> $GITHUB_OUTPUT
+        echo '```terraform' >> $GITHUB_OUTPUT
+        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+        echo '```' >> $GITHUB_OUTPUT
+        echo "</details>" >> $GITHUB_OUTPUT
+        echo "${delimiter}" >> $GITHUB_OUTPUT
+        
+    # Publish Terraform Plan as task summary
+    - name: Publish Terraform Plan to Task Summary
+      env:
+        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+      run: |
+        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+      
+    # If this is a PR post the changes
+    - name: Push Terraform Output to PR
+      if: github.ref != 'refs/heads/main'
+      uses: actions/github-script@v6
+      env:
+        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+      with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const body = `${process.env.SUMMARY}`;
+            github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: body
+            })
